name: Build project

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  buildForWindows:
    name: Build for Windows

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - uses: actions/upload-artifact@v2
        with:
          name: clipboard-listener-windows-64.zip
          path: build/windows/runner/Release/
