name: Build project

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  buildForWindows:
    name: Build for Windows

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.2'
          channel: 'stable'
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows --release
      - run: Compress-Archive -Path build/windows/runner/Release/* -Destination clipboard-listener-windows-64.zip
      - uses: softprops/action-gh-release@v1
        with:
          files: clipboard-listener-windows-64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
